---
- name: 'Unregister the system'
  hosts: 'all'
  become: true

  roles:
    - role: 'b1-systems-ansible-role-suseconnect'
      suseconnect_remove_subscriptions: 'true'
      when: 'ansible_distribution == "SLES"'
