---
- name: 'Gather facts for all hosts'
  hosts: 'all'
  gather_facts: 'yes'
  become: 'true'

- name: 'Install prometheus server and configure it'
  hosts: 'prometheus_server'
  gather_facts: 'yes'
  become: 'true'

  roles:
    - role: 'prometheus_server'
      vars:
        additional_nodes: "{{ groups['prometheus_nodes'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | list }}"
