---

- name: 'Run 10_SLES_register.yml'
  import_playbook: 10_SLES_register.yml

- name: 'Run playbook-all_nodes-add_Prometheus_Grafana_SLES15_repo.yml'
  import_playbook: playbook-all_nodes-add_Prometheus_Grafana_SLES15_repo.yml

- name: 'Run playbook-all_nodes-zypper_ref_accept_keys.yml'
  import_playbook: playbook-all_nodes-zypper_ref_accept_keys.yml

- name: 'Run playbook-all_nodes-install_hostname.yml'
  import_playbook: playbook-all_nodes-install_hostname.yml

- name: 'Run playbook-all_nodes-install_vim-data.yml'
  import_playbook: playbook-all_nodes-install_vim-data.yml

- name: 'Run playbook-all_nodes-minimal_bashrc.yml'
  import_playbook: playbook-all_nodes-minimal_bashrc.yml

- name: 'Run playbook-all_nodes-create_a_vimrc.yml'
  import_playbook: playbook-all_nodes-create_a_vimrc.yml

- name: 'Run playbook-all_nodes-prometheus_node_exporter.yml'
  import_playbook: playbook-all_nodes-prometheus_node_exporter.yml

- name: 'Run playbook-prometheus_server-prometheus_alertmanager.yml'
  import_playbook: playbook-prometheus_server-prometheus_alertmanager.yml

- name: 'Run playbook-prometheus_server-prometheus_server.yml'
  import_playbook: playbook-prometheus_server-prometheus_server.yml

- name: 'Run playbook-prometheus_server-grafana_server.yml'
  import_playbook: playbook-prometheus_server-grafana_server.yml
