---

#
# bootstrap python3.11
#

- name: 'Run playbook-all_nodes-bootstrap_python.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-bootstrap_python.yml

#
# general configuration
#

- name: 'Run playbook-all_nodes-create_a_vimrc.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-create_a_vimrc.yml

- name: 'Run playbook-all_nodes-minimal_tmux_configuration.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-minimal_tmux_configuration.yml

- name: 'Run playbook-all_nodes-minimal_bashrc.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-minimal_bashrc.yml

#
# Prometheus
#

- name: 'Run playbook-all_nodes-add_Prometheus_Grafana_SLES15_repo.yml'
  import_playbook: playbook-all_nodes-add_Prometheus_Grafana_SLES15_repo.yml

- name: 'Run playbook-all_nodes-zypper_ref_accept_keys.yml'
  import_playbook: playbook-all_nodes-zypper_ref_accept_keys.yml

- name: 'Run playbook-all_nodes-update_debian_ubuntu_sources.yml'
  import_playbook: playbook-all_nodes-update_debian_ubuntu_sources.yml

- name: 'Run playbook-all_nodes-install_hostname.yml'
  import_playbook: playbook-all_nodes-install_hostname.yml

- name: 'Run playbook-all_nodes-add_all_nodes_to_etc_hosts.yml'
  import_playbook: playbook-all_nodes-add_all_nodes_to_etc_hosts.yml

- name: 'Run playbook-all_nodes-prometheus_node_exporter.yml'
  import_playbook: playbook-all_nodes-prometheus_node_exporter.yml

- name: 'Run playbook-prometheus_server-prometheus_alertmanager.yml'
  import_playbook: playbook-prometheus_server-prometheus_alertmanager.yml

- name: 'Run playbook-prometheus_server-prometheus_server.yml'
  import_playbook: playbook-prometheus_server-prometheus_server.yml

- name: 'Run playbook-prometheus_server-grafana_server.yml'
  import_playbook: playbook-prometheus_server-grafana_server.yml
