---
- name: 'Install node_exporter on all nodes'
  hosts: 'all'
  gather_facts: 'yes'
  become: 'true'

  roles:
    - role: 'install_one_or_more_packages'
      packages_to_be_installed:
        - 'vim-data'
        - 'hostname'
    - role: 'prometheus_node_exporter'
