---
- name: 'Gather facts for all hosts'
  hosts: 'all'
  gather_facts: true
  become: true

- name: 'Install prometheus server and configure it'
  hosts: 'prometheus_server'
  gather_facts: true
  become: true

  roles:
    - role: 'johanneskastl.prometheus_server'
      additional_nodes: "{{ groups['prometheus_nodes'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | list }}"
      enable_alertmanager: true
      copy_alert_rules_files: true
      alert_rules_files:
        - rules.yml
      alertmanager_static_config_targets:
        - localhost:9093
