---
- name: 'Basic configuration for all nodes'
  hosts: 'prometheus_nodes'
  gather_facts: 'yes'
  become: 'true'

  roles:
    - role: 'zypper_ref_accept_keys'
    - role: 'install_one_or_more_packages'
      vars:
        packages_to_be_installed:
          - 'vim-data'
          - 'hostname'
    - role: 'minimal_bashrc'
      vars:
        additional_users: "{{ ansible_user }}"
    - role: 'create_a_vimrc'
      vars:
        additional_users: "{{ ansible_user }}"
    - role: 'prometheus_node_exporter'

- name: 'Install prometheus server and configure it'
  hosts: 'prometheus_servers'
  gather_facts: 'yes'
  become: 'true'

  roles:
    - role: 'prometheus_server'
      vars:
        additional_nodes: "{{ groups['prometheus_nodes'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | list }}"
